[k8solo-01]
   uuid = "90394897-5956-4F9D-AFC4-E274C45DAB31"
   channel = "stable"
   volume = "data.img"
   cloud_config = "cloud-init/user-data"
   cpus = 2
   memory = 2048
   local = "true"
   offline = "true"
